In [1]:
# 1.	Create a 2D array with 1 on border  and 0 on inside.

import numpy as np

arr = np.zeros((10,10), dtype=int)
arr

arr[0, :] = 1        # first row me sab 1
arr[-1, :] = 1       # last row me sab 1
arr[:, 0] = 1        # first column me sab 1
arr[:, -1] = 1  # last column me sab 1
print(arr)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [4]:
# 2.	Find indices of Non-zero elements from A[2,3,0,1,0,9].

A = np.array([2,3,0,1,0,9])
A

indices = np.nonzero(A)  # return indexes
print(indices)

(array([0, 1, 3, 5]),)


In [1]:
import numpy as np
data = np.array([10, 20, 30, 40, 50])
print("Mean:", np.mean(data))
print("Standard Deviation:", np.std(data))


Mean: 30.0
Standard Deviation: 14.142135623730951


In [15]:
data = np.array([10, 20, 30, 40, 50,60,70,80])
# data[:-6:2]
# data[:-5:-2]
# data[-1:-5:-2]
data[:-5:3]
# data[:-5:-5]

array([10])

In [2]:
# 3.	Create a zero  one D vector of size 10 but 5th value should be 9.
A = np.zeros(10, dtype=int)
A[5] = 9
print(A)

[0 0 0 0 0 9 0 0 0 0]
