In [1]:
# 1.	Create a 2D array with 1 on border  and 0 on inside.

import numpy as np

arr = np.zeros((10,10), dtype=int)
arr

arr[0, :] = 1        # first row me sab 1
arr[-1, :] = 1       # last row me sab 1
arr[:, 0] = 1        # first column me sab 1
arr[:, -1] = 1  # last column me sab 1
print(arr)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [4]:
# 2.	Find indices of Non-zero elements from A[2,3,0,1,0,9].

A = np.array([2,3,0,1,0,9])
A

indices = np.nonzero(A)  # return indexes
print(indices)

(array([0, 1, 3, 5]),)
