In [1]:
import numpy as np

x = ([[1,2,3,4,5,]])
x


[[1, 2, 3, 4, 5]]

In [2]:
for i in x:
    for c in i:
        print(c)

1
2
3
4
5


In [5]:
for d in np.nditer(x):
    print(d)

1
2
3
4
5


In [8]:
# indexing check karne ke liye

for i,d in np.ndenumerate(x):
    print(i,d)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5


In [11]:
k = np.zeros(3)
k

array([0., 0., 0.])

In [14]:
p = np.empty([9,2])
p

e = np.empty([9,2], dtype=int)
e

array([[31244194863382593, 30399718394495086],
       [29555332122607727, 32369759767429230],
       [28429432215765103, 31525674135060596],
       [32651513917735013,  9007671708418153],
       [30399800003199075, 31244194863382628],
       [28429393556668532, 30681249209319456],
       [32651531097210992, 29555010000126053],
       [28147931469906029, 28429470870339689],
       [          7929964,        4294967296]])

In [15]:
k = np.ones(3)
k

array([1., 1., 1.])

In [16]:
k = np.eye(3)
k

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [2]:
a = [1,3,4,56,4,5,6]
a

[1, 3, 4, 56, 4, 5, 6]

In [4]:
import numpy as np

In [9]:
A = np.array([[1,2,3,4,5],[6,7,8,9,10]])
A
np.ndim(A)
np.shape(A)

(2, 5)

In [6]:
w = A.T
w

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [7]:
B = np.transpose([[1,2,3,4,5],[6,7,8,9,10]])
B

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [10]:
s = np.array([20,45,46,55,98])
# where

sp = np.array([-20,45,-46,55,-98])
sp

array([-20,  45, -46,  55, -98])

In [11]:
k = np.where(sp>0,1,sp)
k

array([-20,   1, -46,   1, -98])

In [ ]:
# Mathematical and Statical functions

